//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1640.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinMaster
    {
        public int MTransNo { get; set; }
        public string BarCode { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string BinWash { get; set; }
        public string BinCondition { get; set; }
        public string BinFillStatus { get; set; }
        public string BinStatus { get; set; }
    }
}
