//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1640.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int MTransNo { get; set; }
        public string CompCode { get; set; }
        public string CompName { get; set; }
        public string Natureofwork { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string State { get; set; }
        public Nullable<int> StateCode { get; set; }
        public string PhoneNo { get; set; }
        public string GeneralEmail { get; set; }
        public string SalesEmail { get; set; }
        public string PurchaseEmail { get; set; }
        public string Website { get; set; }
        public string GSTIN { get; set; }
        public string PAN { get; set; }
        public string CIN { get; set; }
        public string BankName { get; set; }
        public string BranchName { get; set; }
        public string IFSCCode { get; set; }
        public string AccountNo { get; set; }
        public string MICRCode { get; set; }
        public Nullable<System.DateTime> FromYear { get; set; }
        public Nullable<System.DateTime> ToYear { get; set; }
        public Nullable<byte> LockCounter { get; set; }
        public string LockStatus { get; set; }
        public Nullable<short> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<short> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string DeleteStatus { get; set; }
        public Nullable<decimal> TimeDefiance { get; set; }
        public string IECNO { get; set; }
        public Nullable<int> PinCode { get; set; }
        public string Country { get; set; }
        public string BDTPhoneNo { get; set; }
        public string DesignPhoneNo { get; set; }
        public string PlanningPhoneNo { get; set; }
        public string PurchasePhoneNo { get; set; }
        public string QualityPhoneNo { get; set; }
        public string StorePhoneNo { get; set; }
        public string ProductionPhoneNo { get; set; }
        public string AccountPhoneNo { get; set; }
        public string HRPhoneNo { get; set; }
        public string SalesEmail1 { get; set; }
        public string SalesEmail2 { get; set; }
        public string SalesEmail3 { get; set; }
    }
}
