//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1640.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMSMsg
    {
        public int MTransNo { get; set; }
        public string Messages { get; set; }
        public Nullable<int> Sender { get; set; }
        public Nullable<int> Receiver { get; set; }
        public string MsgStatus { get; set; }
        public Nullable<System.DateTime> SendOn { get; set; }
        public string AckStatus { get; set; }
        public Nullable<System.DateTime> AckDate { get; set; }
    }
}
