//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1640.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAuthorization
    {
        public int MTransNo { get; set; }
        public int UserNo { get; set; }
        public int ModuleNo { get; set; }
        public string AuthType { get; set; }
        public string Dept { get; set; }
        public Nullable<int> BranchNo { get; set; }
    }
}
