//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1640.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMaster
    {
        public int MTransNo { get; set; }
        public string UserName { get; set; }
        public string UserId { get; set; }
        public string PW { get; set; }
        public string UserType { get; set; }
        public Nullable<byte> LockCounter { get; set; }
        public string LockStatus { get; set; }
        public Nullable<short> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<short> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string DeleteStatus { get; set; }
        public Nullable<short> SubscID { get; set; }
        public Nullable<System.DateTime> loginDate { get; set; }
        public string EmailId { get; set; }
    }
}
